spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health,sample-health
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
#    key-store: classpath:keystore/app-https.p12
    key-store: ./keystore/app-https.p12
    key-store-password: changeit
    key-alias: app-https
#    trust-store: classpath:keystore/app-https.p12
#    trust-store-type: PKCS12
#    trust-store-password: changeit

#management.server.port=9001
#management.security.enable=true