spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health,sample-health


#management.server.port=9001
#management.security.enable=true