CREATE DATABASE sample;

USE sample;

CREATE TABLE sample.SAMPLE (
	 id INT NOT NULL AUTO_INCREMENT, 
	 content VARCHAR(100) NOT NULL,
	 version INT NOT NULL, 
	 PRIMARY KEY (id)
); 

CREATE TABLE sample.AUTH_EXPR(
	resource 		VARCHAR(200) NOT NULL,
	policy_expr 	VARCHAR(500) NOT NULL
);

INSERT INTO SAMPLE (ID, CONTENT, VERSION) VALUES (5000, 'hi im going to be deleted', 0);
INSERT INTO SAMPLE (ID, CONTENT, VERSION) VALUES (0, 'hi im a sample', 0);
INSERT INTO AUTH_EXPR (RESOURCE, POLICY_EXPR) VALUES ('/', 'true');
INSERT INTO AUTH_EXPR (RESOURCE, POLICY_EXPR) VALUES ('/sample.*', 'hasRole(''ROLE_USERS'')');
INSERT INTO AUTH_EXPR (RESOURCE, POLICY_EXPR) VALUES ('/read', 'hasRole(''ROLE_USERS'')');
INSERT INTO AUTH_EXPR (RESOURCE, POLICY_EXPR) VALUES ('/logout', 'true');
INSERT INTO AUTH_EXPR (RESOURCE, POLICY_EXPR) VALUES ('.*html', 'true');

COMMIT;