apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: default-node
        - containerPort: 9001
          name: management-port
        env:
        - name: DB_HOST
          value: "app-db-service"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: APP_DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: APP_DB_PASSWORD
        startupProbe:
          httpGet:
            path: /actuator/health
            port: management-port
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: management-port
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/sample-health
            port: management-port
          initialDelaySeconds: 60
          periodSeconds: 60

        