apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app.k8:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8443
          name: default-node
        - containerPort: 9001
          name: management-port
        volumeMounts:
          - mountPath: "/app-https-keystore"
            name: app-https
            readOnly: true
        env:
        - name: DB_HOST
          value: "app-db-service"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: APP_DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: APP_DB_PASSWORD
        startupProbe:
          httpGet:
            path: /actuator/health
            port: management-port
            scheme: HTTPS
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: management-port
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/sample-health
            port: management-port
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
        - name: app-https
          secret:
            secretName: app-https-secret
        